---
title: "Map making"
output: html_document
date: '2025-04-11'
---

```{r}
library(sf)
```

```{r}



# Define output file name and resolution
pdf(here("figs","food_waste_score_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = log(fw_score_weighted)), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Weighted Value") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()

#######






# Define output file name and resolution
pdf(here("figs","renter_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = log(rent_pct)), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Weighted Value") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","conifer_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = log(Conifer)), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Weighted Value") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","grass_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = log(ModGrassHerb)), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Weighted Value") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","food_retail_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = Food_Retail), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Weighted Value") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","chinese_pct_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = chinese_pct), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Chinese_pct") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","food_stores_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(joined) +
  geom_sf(aes(fill = food_stores), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "food_stores") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","nearest_food_retail_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = nearest_food_retail), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "nearest_food_retail") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","pct_rent_subsidized_map_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_combined) +
  geom_sf(aes(fill = pct_rent_subsidized), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "pct_rent_subsidized") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","pct_rent_thirty_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = pct_rent_thirty), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "pct_rent_thirty") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","notsuitable_majorrepairs_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = notsuitable_majorrepairs), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "notsuitable_majorrepairs") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","pct_housing_notsuitables_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = pct_housing_notsuitable), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "pct_housing_notsuitable") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","poorserivce_housing_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = poorservice_housing), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "poorservice_housing") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","NaturalVegSum_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = NaturalVegSum), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NaturalVegSum") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","NaturalVegSum_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = NaturalVegSum), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NaturalVegSum") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","Deciduous_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Deciduous), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Deciduous") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()





# Define output file name and resolution
pdf(here("figs","Conifer_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Conifer), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Conifer") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","Shrub_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Shrub), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Shrub") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","NatGrassHerb_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = NatGrassHerb), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NatGrassHerbb") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","Soil_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Soil), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Soil") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","Barren_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Barren), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Barren") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","NonphotoVeg_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = NonphotoVeg), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NonphotoVeg") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()

# Define output file name and resolution
pdf(here("figs","Shadow_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Shadow), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Shadow") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","Water_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Water), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Water") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()

# Define output file name and resolution
pdf(here("figs","OtherBuilt_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = OtherBuilt), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "OtherBuilt") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","landcover_sites.pdf"), width = 20, height = 14)  # Adjust size as needed

plot(lcc2020_van)
plot(st_geometry(sites_3857), add = TRUE,  lwd = 2)

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","landcover_sites.pdf"), width = 20, height = 14)  # Adjust size as needed

plot(lc)

# Close the PDF device to save the file
dev.off()





# Define output file name and resolution
pdf(here("figs","NaturalVegSum2_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = NaturalVegSum2), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NaturalVegSum2") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()





# Define output file name and resolution
pdf(here("figs","Deciduous_750m_fromdatgrid.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid) +
  geom_sf(aes(fill = Deciduous), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Deciduous") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","Conifer_750m_fromdatgrid.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid) +
  geom_sf(aes(fill = Conifer), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Conifer") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","Conifer_750m_fromjoined.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(joined) +
  geom_sf(aes(fill = Conifer), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Conifer") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","Conifer_750m_from1stdat_grid_final.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = Conifer), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Conifer") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","Conifer_750m_from2nddat_grid_final.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = Conifer), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Conifer") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","NaturalVegSum_750m_from2nddat_grid_final.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = NaturalVegSum), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NaturalVegSum") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","NaturalVegSum_750m_from_dat_clean.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_clean) +
  geom_sf(aes(fill = NaturalVegSum), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NaturalVegSum") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","NaturalVegSum_750m_from_dat_scaled2.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = NaturalVegSum), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "NaturalVegSum") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","Conifer_750m_from_dat_clean.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_clean) +
  geom_sf(aes(fill = Conifer), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Conifer") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","rent_pct_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = rent_pct), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "percent renters") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","pop_km_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = pop_km), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Pop. per sq. km.") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","population_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = population), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Population") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","population2_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = Population), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Population") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","fw_score_weighted_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = fw_score_weighted), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "fw_score_weighted") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","total_repairs_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = total_repairs), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Total Repairs") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","major_repairs_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = major_repairs), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Major Repairs") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","minor_repairs_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = minor_repaires), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "Minor Repairs") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()





# Define output file name and resolution
pdf(here("figs","pct_housing_notsuitable_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = pct_housing_notsuitable), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "pct_housing_notsuitable") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","pct_rent_subsidized_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = pct_rent_subsidized), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "pct_rent_subsidized") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



# Define output file name and resolution
pdf(here("figs","rent_subsidized_int_750m.pdf"), width = 80, height = 64)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = dat_scaled$rent_subsidized_int), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "rent_subsidized_int") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","service_road_length_750m.pdf"), width = 20, height = 15)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = dat_grid_final$service_road_length_m), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "service_road_length_m") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","log_service_road_dist_750m.pdf"), width = 20, height = 15)  # Adjust size as needed

ggplot(dat_grid_final) +
  geom_sf(aes(fill = log(dat_grid_final$dist_to_service_road_m)), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "dist_to_service_road_m") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()


# Define output file name and resolution
pdf(here("figs","log_service_road_dist_750m.pdf"), width = 20, height = 15)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = log(dat_scaled$dist_to_service_road_m)), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "dist_to_service_road_m") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()




# Define output file name and resolution
pdf(here("figs","service_road_weight.pdf"), width = 20, height = 15)  # Adjust size as needed

ggplot(dat_scaled) +
  geom_sf(aes(fill = service_road_weight), color = NA) +  # No borders for a smooth heatmap
  scale_fill_viridis_c(option = "inferno", name = "service_road_weigh") +  # "inferno" for bright-darker range
  theme_minimal() +
  theme(panel.grid = element_blank())  # Remove grid lines for a cleaner look

# Close the PDF device to save the file
dev.off()



library(dplyr)
library(sf)

# Group by site and create a centroid per group
site_labels <- dat_grid_final %>%
  group_by(site) %>%
  summarise(geometry = st_union(geometry)) %>%       # Combine all grid cells per site
  mutate(label_point = st_centroid(geometry))        # Get a label point per site



# Save plot to PDF
pdf(here("figs","service_road_length_750m.pdf"), width = 20, height = 15)

ggplot(dat_scaled) +
  geom_sf(aes(fill = service_road_length_m), color = NA) +  # Fill grid by road length
  geom_sf(data = site_labels, aes(geometry = label_point), inherit.aes = FALSE) +  # Ensure geom_sf works with label geometry
  geom_sf_text(data = site_labels, aes(geometry = label_point, label = site), size = 6, fontface = "bold") +
  scale_fill_viridis_c(option = "inferno", name = "service_road_length_m") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()



# Save plot to PDF
pdf(here("figs","service_road_bool_750m.pdf"), width = 20, height = 15)

ggplot(dat_scaled) +
  geom_sf(aes(fill = service_road_bool), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "service_road_bool") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()





# Save plot to PDF
pdf(here("figs","service_road_weight_750m_3.pdf"), width = 20, height = 15)

ggplot(dat_scaled) +
  geom_sf(aes(fill = service_road_weight), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "service_road_weight") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()




# Save plot to PDF
pdf(here("figs","pct_major_repairs_750m_3.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = pct_major_repairs), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "pct_major_repairst") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","pct_minor_repairs_750m_3.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = pct_minor_repairs), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "pct_minor_repairs") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","total_repairs_750m_3.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = total_repairs), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "total_repairs") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","pct_rent_subsidized_750m_3.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = pct_rent_subsidized), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "pct_rent_subsidized") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","housing_suitability_750m_3.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = housing_suitability), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "housing_suitability") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","pct_unsuitable_housing_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = pct_unsuitable_housing), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "pct_unsuitable_housing") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()



# Save plot to PDF
pdf(here("figs","separated_divorced_widowed_pct_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = separated_divorced_widowed_pct), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "separated_divorced_widowed_pct") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","live_alone_pct_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = live_alone_pct), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "live_alone_pct") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()



# Save plot to PDF
pdf(here("figs","live_alone_pct_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = live_alone_pct), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "live_alone_pct") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


# Save plot to PDF
pdf(here("figs","one_parent_pct_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = one_parent_pct), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "one_parent_pct") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()



# Save plot to PDF
pdf(here("figs","avg_household_size_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = avg_household_size), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "avg_household_size") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()



pdf(here("figs","avg_household_size_750m.pdf"), width = 20, height = 15)

ggplot(dat_grid_final) +
  geom_sf(aes(fill = avg_household_size), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "avg_household_size") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


pdf(here("figs","Factor1_750m_2.pdf"), width = 20, height = 15)

ggplot(dat_combined) +
  geom_sf(aes(fill = Factor1), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "Factor1") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


pdf(here("figs","Factor2_750m.pdf"), width = 20, height = 15)

ggplot(dat_combined) +
  geom_sf(aes(fill = Factor2), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "Factor2") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()



pdf(here("figs","Factor3_750m.pdf"), width = 20, height = 15)

ggplot(dat_combined) +
  geom_sf(aes(fill = Factor3), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "Factor2") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()


pdf(here("figs", "fw_score_weighted_750m.pdf"), width = 10, height = 8)

ggplot(dat_no_ub) +
  geom_sf(aes(fill = fw_score_weighted), color = NA) +
  scale_fill_viridis_c(
    option = "inferno",
    name = "fw_score_weighted",
    limits = c(0.0000001, 0.5)  # Set min and max of color scale
  ) +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()





# Save plot to PDF
pdf(here("figs","van_service_road_weight_750m.pdf"), width = 20, height = 15)

ggplot(van_dat) +
  geom_sf(aes(fill = service_road_weight), color = NA) +  # Fill grid by road length
  scale_fill_viridis_c(option = "inferno", name = "service_road_weight") +
  theme_minimal() +
  theme(panel.grid = element_blank())

dev.off()

```
